MyTour/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tours.urls', namespace='tours'))
]

tours/urls.py
from . import views
from django.urls import path

app_name= 'tours'

urlpatterns = [
    path('', views.base, name='main'),
    path('booking/', views.booking, name='booking'),
    path('booking/readmore', views.readmore, name='readmore'),
    path('register/', views.register, name='register'),
]

tours/models.py
from django.db import models
from django.core.exceptions import ValidationError

class New_bookings(models.Model):
    title_name = models.CharField(' Называние', max_length=20)
    title_text = models.TextField('Описание')
    photo = models.URLField('Фотография', null=True, blank=True)

    def __str__(self):
        return self.title_name

    class Meta:
        verbose_name = 'Курорт'
        verbose_name_plural = 'Курорттар'


class Booking(models.Model):
    name = models.CharField(max_length=30, verbose_name='Аты')
    phone_number = models.CharField(max_length=20, verbose_name='Телефон номері')
    booking_date = models.DateField(verbose_name='Брондау уақыты')
    resort = models.ForeignKey(New_bookings, on_delete=models.CASCADE, verbose_name='Курорт')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Брондау'
        verbose_name_plural = 'Брондаулар'

    def clean(self):
        existing_booking = Booking.objects.filter(booking_date=self.booking_date, resort=self.resort).exists()
        if existing_booking:
            raise ValidationError("Бұл уақыт бұрыннан брондалған. Басқа күнді таңдаңыз.")

tours/forms.py
from django import forms
from .models import Booking, New_bookings


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['name', 'phone_number', 'booking_date', 'resort']
        widgets = {
            'booking_date': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['resort'].queryset = New_bookings.objects.all()

tours/views.py

from .models import New_bookings
from django.shortcuts import render, redirect
from .forms import BookingForm
from django.contrib import messages


def base(request):
    return render(request, 'index.html')


def booking(request):
    bookings = New_bookings.objects.all()
    return render(request, 'booking.html', {'bookings': bookings})


def register(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'success.html')
        else:
            messages.error(request, "Бұл уақыт брондалған. Басқа күнді таңдаңыз.")
    else:
        form = BookingForm()
    return render(request, 'register.html', {'form': form})


def readmore(request):
    return render(request, 'readmore.html')

templates/booking.html
{% extends 'index.html' %}
{% load static %}
{% block style %}
.hero_area {
    position: relative;
    min-height: 20vh;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
}
{% endblock %}
{% block content %}

  <div class="hero_area">

    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg-low.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'tours:main' %}">
            <span>
              My Tour
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'tours:main' %}">Үйге </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'tours:main' %}"> Біз туралы <span class="sr-only">(current)</span> </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tours:booking' %}">Брондау</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>


  <!-- service section -->

  <section class="service_section layout_padding">
    <div class="service_container">
      <div class="container ">
        <div class="heading_container heading_center">
          <h2>
            БРОНДАУҒА <span>БОЛАДЫ</span>
          </h2>
        </div>
        <div class="row">
          {% for el in bookings %}
          <div class="col-md-4 ">
            <div class="box ">
              <div class="img-box">
                {% if el.photo %}
                  <img src="{{ el.photo }}" alt="{{ el.title_name }}">
                {% else %}
                <img src="https://cdn.nur.kz/images/720/c56513dd3427f16c.webp" alt="">
                {% endif %}
              </div>
              <div class="detail-box">
                <h5>
                  {{ el.title_name }}
                </h5>
                <p>
                  {{ el.title_text }}
                </p>
                <a href="{% url 'tours:booking' %}">
                  Толығырақ
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="btn-box">
          <a href="{% url 'tours:register' %}">
            Брондау
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- end service section -->

{% endblock %}

templates/readmore.html
{% extends 'booking.html' %}
{% load static %}

{% block content %}

<div class="hero_area">

    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg-low.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'tours:main' %}">
            <span>
              My Tour
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'tours:main' %}">Үйге </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'tours:main' %}"> Біз туралы <span class="sr-only">(current)</span> </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tours:booking' %}">Брондау</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

{% endblock %}

templates/register.html
{% extends 'index.html' %}
{% load static %}
{% block style  %}
.hero_area {
    position: relative;
    min-height: 20vh;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
}
.booking {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin-top: 20px;
    padding: 20px;
}

.input-row {
    display: flex;
    flex-direction: column;
    width: 100%;
}

.input-column {
    margin: 10px 0;
    display: inline-block;
    vertical-align: top; 3

}

input[type="text"],
input[type="date"] {
    width: 10%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

p {
    font-weight: bold;
}

{% endblock %}
{% block content %}
<div class="hero_area">
    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg-low.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'tours:main' %}">
            <span>
              My Tour
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'tours:main' %}">Үйге </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'tours:main' %}"> Біз туралы <span class="sr-only">(current)</span> </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tours:booking' %}">Брондау</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
    {% endif %}
    <form method="post">
        <div class="booking">
            {% csrf_token %}
    <div class="input-row">
        <div class="input-column">
            <p>Аты: {{ form.name }}</p>
        </div>
        <div class="input-column">
            <p>Телефон номері: {{ form.phone_number }}</p>
        </div>
        <div class="input-column">
            <p>Брондау уақыты: {{ form.booking_date }}</p>
        </div>
        <div class="input-column">
            <p>Курорт: {{ form.resort}}</p>

        </div>

    </div>
        <button type="submit" class="nav-link">Брондау</button></div>
    </form>



{% endblock %}

templates/success.html
{% extends 'index.html' %}
{% load static %}
{% block style %}
h1 {
    padding: 50px 0;
    font-size: 48px; /* Задаем большой размер шрифта */
    text-align: center; /* Центрируем текст по горизонтали */
    color:White;
}

.nav-link {
<!--    display: inline-block;-->
<!--    padding: 10px 20px;-->
<!--    margin-top: 20px;-->
<!--    background-color: #007bff;-->
<!--    color: #fff;-->
<!--    border: none;-->
<!--    border-radius: 5px;-->
<!--    text-align: center;-->
<!--    text-decoration: none;-->
<!--    transition: background-color 0.3s;-->
padding: 50px 0;
}

.nav-link:hover {
    background-color: #0056b3;
}
.container {
    text-align: center;
}

.nav-link-container {
    display: inline-block;
    margin-top: 28px;
}
{% endblock %}
{% block content %}
<div class="hero_area">

    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg-low.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'tours:main' %}">
            <span>
              My Tour
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'tours:main' %}">Үйге </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'tours:main' %}"> Біз туралы <span class="sr-only">(current)</span> </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tours:booking' %}">Брондау</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->

<h1>Cіз тіркелдіңіз!!</h1>
<div class="container">
    <div class="nav-link-container">
        <a class="nav-link" href="{% url 'tours:main' %}">Басты бетке қайту <span class="sr-only"></span></a>
    </div>
</div>


{% endblock %}